#logistic regression
train<-read.csv("H:\\data science\\data science\\case study 2\\train.csv",header=T,sep=",",na.strings=c(""))
test<-read.csv("H:\\data science\\data science\\case study 2\\test.csv",header=T,sep=",",na.strings=c(""))
summary(train)
str(train)
boxplot(train$Age)
library(Hmisc)
library(e1071)
skewness(train$Age)
boxplot(train$Fare)
skewness(train$Fare)
describe(train)
#convert to factor
train$Survived<- as.factor(train$Survived)
train$Pclass<- as.factor(train$Pclass)
str(train)
#missing value imputation
train$Age<-ifelse(is.na(train$Age),median(train$Age,na.rm = T),train$Age)
sum(is.na(train$Age))
#missing value imputation - embarked
sum(is.na(train$Embarked))
table(train$Embarked)
train$Embarked<-as.character(train$Embarked)# converted into character
train$Embarked<- ifelse(is.na(train$Embarked),'S',(train$Embarked))
train$Embarked<-as.factor(train$Embarked)#converted into factor
summary(train)
str(train)
skewness(train$Age)
cor(train$Age,train$Fare)
cor(train$SibSp,train$Parch)
names(train)
model<-glm(Survived~Pclass+Sex+Age+SibSp+Parch+Fare+Embarked,family = 'binomial',data = train)
summary(model)
train$preds<- predict(model,train,type = 'response')
train$outcome<-ifelse(train$preds>=.5,1,0)
table(train$Survived,train$outcome)
#MODEL 2
train$ln_fare<- log(train$Fare)
train$ln_fare<-ifelse(train$ln_fare==-Inf,0,train$ln_fare)
model2<-glm(Survived~Pclass+Sex+Age+SibSp+Parch+ln_fare+Embarked,family = 'binomial',data = train)
table(train$Survived,train$ln_fare)
summary(model2)
train$preds<- predict(model2,train,type = 'response')
train$outcome<-ifelse(train$preds>=.5,1,0)
table(train$Survived,train$outcome)
#---test data set-------
str(test)
test$Pclass<-as.factor(test$Pclass)
test$Age<-ifelse(is.na(test$Age),median(test$Age,na.rm=T),test$Age)
sum(is.na(test$Age))
test$Fare<-ifelse(is.na(test$Fare),median(test$Fare,na.rm=T),test$Fare)
sum(is.na(test$Fare))
describe(test)
summary(test)
test$preds<-predict(model,test,type = "response")
test$outcome<-ifelse(test$preds<=0.50,0,1)
write.csv(test,'finalpreds.csv')
getwd()

install.packages("party")
library(party)
install.packages("grid")
library(grid)
install.packages("mvtnorm")
library(mvtnorm)
install.packages("modeltools")
library(modeltools)
install.packages("stats4")
library(stats4)
install.packages("strucchange")
library(strucchange)
install.packages("zoo")
library(zoo)
install.packages("sandwich")
library(sandwich)



png(file='decision_tree.png')
names(train)
model_tree<-ctree(Survived~Pclass+Sex+Age+SibSp+Parch+ln_fare+Embarked,data = train)
#plot tree
plot(model_tree)
dev.off()
summary(model_tree)
#####random forest#####
install.packages('randomForest')
library(randomForest)
model_rf<-randomForest(Survived~Pclass+Sex+Age+SibSp+Parch+Fare+Embarked,data = train)
summary(model_rf)
